config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # devise_for :user do
  #   get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
  root to: 'pages#home'

  resources :users

  resource :profile

  resources :relationships, only: %i[index new create] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :donations, only: [:index]
  namespace :receiver do
    resources :donations, only: [:index] do
      member do
        patch :choose
      end
    end
  end

  namespace :giver do
    resources :donations, only: %i[index new create] do
      member do
        patch :confirm
      end
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
    
    def resource_name
        :user
    end

    def resource
    @resource ||= User.new
    end

    def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
    end
    
    private
    
    def add_default_avatar
        unless avatar.attached?
            avatar.attach(
            io: File.open(
                Rails.root.join(
                'app', 'assets', 'images', 'default_profile.jpg'
                )
            ), 
            filename: 'default_profile.jpg',
            content_type: 'image/jpg'
            )
        end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
    @donations = current_user.donations
  end

  def profile_params
  params.require(:profile).permit(:photo, :avatar)
end

end

app/views/profiles/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="tabs-underlined">
      <h3 class="top-bar-dons text-center tab-underlined active relationships">Mon profil</h3>
      </div>
      <div class="user-header col-12 pt-5">
        <div class="field">
          <%# <%= image_tag(current_user.avatar_thumbnail, class: "user-avatar")%>
          <%#= image_tag @user.avatar.variant(resize_to_fit: [120, 120]) %>
          <%= cl_image_tag @current_user.avatar.key, height: 120, width: 120, crop: :fill if @current_user.avatar.attached?%>
        </div>

        <p><%= @user.first_name %> <%= @user.last_name %></p>
      </div>
      <div class="donation-p col-12 text-center ">
        <div class="stats" id="text-stat">
          <% if @user.donations.count == 0 %>
            <p>N'hésite pas à donner !</p>
          <% elsif @user.donations.count == 1 %>
            <p>1 don effectué ! Continue comme ça !</p>
          <% else @user.donations.count >= 2 %>
            <p><%= @user.donations.count %> dons effectués !</p>
          <% end %>
        </div>
        <div class="text-center-params-user">
          <div class="btn-params-user">
            <%= link_to("Modifier mon compte", edit_user_registration_path(current_user)) %>
          </div>
          <div class="btn-del-user">
            <%= link_to "Supprimer mon compte", registration_path(current_user), method: :delete, data: { confirm: "Vous êtes certain ? une fois supprimé vous ne pourrez pas vous inscrire avec la même adresse mail." } %>
          </div>
        </div>
      </div>
      <div class="donation-p col-12">
        <div class="form-actions pt-3">
          <%= link_to("Se déconnecter", destroy_user_session_path, method: :delete,  class: "btn btn-logout cta text-center ")%>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- FOOTER ADD RELATIONSHIP -->
<%= render 'shared/relationships_footer' %>