config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # devise_for :user do
  #   get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
  root to: 'pages#home'

  resources :users

  resource :profile

  resources :relationships, only: %i[index new create] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :donations, only: [:index]
  namespace :receiver do
    resources :donations, only: [:index] do
      member do
        patch :choose
      end
    end
  end

  namespace :giver do
    resources :donations, only: %i[index new create] do
      member do
        patch :confirm
      end
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :status, presence: true, inclusion: { in: ["pending", "accepted", "declined"] }
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
# frozen_string_literal: true

  before_action :set_relationship, only: [:accept, :decline]

  def index
    @relationship_requests = current_user.relationship_requests

    @friends = current_user.friends
  end

  def new
    @relationship = Relationship.new
  end

  def create
    @user = current_user
    @relationship = Relationship.new(relationship_params)
    @relationship.user = current_user
    @relationship.save
    redirect_to relationships_path
  end

  def accept
    @relationship.status = "accepted"
    @relationship.save
    redirect_to relationships_path
  end

  def decline
    @relationship.status = "declined"
    @relationship.save
    redirect_to relationships_path
  end

  private

  def set_relationship
    @relationship = Relationship.find(params[:id])
  end

  def relationship_params
    params.require(:relationship).permit(:friend_id, :user_id)
  end
end

app/views/relationships/_card.html.erb
<div class="card mt-2" style="min-width: auto;">
  <div class="card-avatar relationships">
    <div class="avatar">
      <%= cl_image_tag(user.avatar, height: 64, width: 64, crop: :fill, gravity: :face) %>
    </div>
  </div>
  <div class="card-content">
    <div class="row-card-content" id="first-row">
      <div class="card-content-deadline" style="padding-top: 19px;"></div>
    </div>
    <div class="row-card-content" id="second-row">
      <div class="card-content-username" style="margin-top: -10px;">
        <p><%= user.first_name %> <%= user.last_name %></p>
      </div>
    </div>
    <div class="card-content-links text-center" style="margin-top: -15px; padding-left: 150px; margin-left: -36px; margin-top: -34px;">
       <%= simple_form_for Relationship.new do |f| %>
        <%= f.input :friend_id, as: :hidden, input_html: { value: user.id } %>
        <%= f.submit "Inviter", class: "btn link-success" %>
       <% end %>
    </div>
  </div>
</div>

app/views/relationships/_cards.html.erb
<% users.each do |user| %>
  <%= render 'relationships/card', user: user %>
<% end %>

app/views/relationships/index.html.erb
<% if @relationship_requests.any? %>
  <div class="container">
    <div class="row">
      <div class="col-12 list-relationships tabs-underlined">
        <h3 class="top-bar-dons text-center tab-underlined active relationships">Mes invitations</h3>
      </div>
    </div>
  </div>
<% end %>

<div class="container container-relationship">
  <div class="row">
    <% @relationship_requests.each do |relationship_request| %>
      <div class="col-12 card">
        <div class="card-avatar relationships">
          <div class="avatar">
            <%= cl_image_tag(relationship_request.user.avatar, height: 64, width: 64, crop: :fill, gravity: :face) %>
          </div>
        </div>
        <div class="card-content">
          <div class="row-card-content" id="first-row">
            <div class="card-content-deadline" style="padding-top: 19px;">
              <!-- <p><%#= cl_image_tag "iconecard/horloge.svg" %>&nbsp;&nbsp;20/11/2019</p> -->
            </div>
          </div>
          <div class="row-card-content" id="second-row">
            <div class="card-content-username" style="margin-top: -10px;">
              <p><%= relationship_request.user.first_name %></p>
            </div>
          </div>
          <div class="card-content-links text-center" style="margin-top: -15px;">
            <%= link_to "Accepter", accept_relationship_path(relationship_request), method: :patch, class: "btn link-success" %>&nbsp;&nbsp;&nbsp;
            <%= link_to "Refuser", decline_relationship_path(relationship_request), method: :patch, class: "btn link-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container" style="padding-bottom: 60px;">
  <div class="row">
    <% if @friends.empty? %>
      <h1>Il est temps de <strong>frigoter</strong> !</h1>
    <% else %>
      <div class="col-12 list-relationships tabs-underlined">
        <h3 class="top-bar-dons text-center tab-underlined active relationships">Ma liste d'amis</h3>
      </div>
        <% @friends.each do |friend| %>
          <div class="col-12 card mb-2" style="padding-bottom: 60px;">
            <div class="card-avatar relationships">
              <div class="avatar">
                <%= cl_image_tag(friend.avatar, height: 64, width: 64, crop: :fill, gravity: :face) %>
              </div>
            </div>
            <div class="card-content">
              <div class="row-card-content" id="first-row">
                <div class="card-content-deadline" style="padding-top: 22px;">
                <!-- <p><%#= cl_image_tag "iconecard/horloge.svg" %>&nbsp;&nbsp;20/11/2019</p> -->
                </div>
              </div>
              <div class="row-card-content" id="second-row">
                <div class="card-content-username" style="margin-top: -15px;">
                  <p><%= friend.first_name %></p>
                </div>
              </div>
              <div class="card-content-address">
                <%= link_to friend.address, google_maps_itinerary(friend.address), target: "_blank" %>
                <%#= friend.address %>
              </div>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

<%= render 'shared/relationships_footer' %>

app/views/relationships/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-xs-12" style="padding-bottom: 60px;">
      <div class="friend-header pt-3">
        <div class="col-12 list-relationships tabs-underlined">
          <h3 class="top-bar-dons text-center tab-underlined active relationships">Ajouter un nouvel ami</h3>
        </div>
      </div>
      <div class="logo-friend pt-3 text-center">
        <%=cl_image_tag("friend-icon.png")%>
      </div>
      <div class="form-group pt-5" style="margin-top: -1em;">
        <%= form_tag users_path, method: :get, class: 'input-group', remote: true do %>
          <%= text_field_tag :search,
            params[:search],
            class: "form-control",
            placeholder: "Prénom, nom ou e-mail"
          %>
          <span>
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-search"></i>
            </button>
          </span>
        <% end %>
        <div id="cards-container" style="margin-top: 1em;">
          <%#= render 'relationships/card', user: User.first %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/relationships_footer' %>