config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # devise_for :user do
  #   get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
  root to: 'pages#home'

  resources :users

  resource :profile

  resources :relationships, only: %i[index new create] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :donations, only: [:index]
  namespace :receiver do
    resources :donations, only: [:index] do
      member do
        patch :choose
      end
    end
  end

  namespace :giver do
    resources :donations, only: %i[index new create] do
      member do
        patch :confirm
      end
    end
  end
end

app/views/shared/_donations_footer.html.erb
<!-- FOOTER -->
</div>
  <div class="footer">
    <div class="footer-element footer-icon <%= 'active' if current_page?('/donations') %>">
      <%= link_to donations_path do %>
        <%= cl_image_tag "iconefooter/home.svg" %>
      <% end %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/receiver/donations') %>">
      <%= link_to receiver_donations_path do %>
        <%= cl_image_tag "iconefooter/panier.svg" %>
      <% end %>
    </div>
    <div class="footer-element">
        <%= cl_image_tag "iconefooter/signeplus.svg", data: { toggle: "modal", target: "#donationNewModal" } %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/profile') %>">
      <%= link_to(profile_path) do %>
        <%= cl_image_tag "iconefooter/user.svg" %>
      <% end %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/relationships') %>">
      <%= link_to relationships_path do %>
        <%= cl_image_tag "iconefooter/contact.svg" %>
      <% end %>
    </div>
  </div>
</div>

<!-- MODAL -->
<%= render 'shared/modal_add_donations' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'iconepwa/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'iconepwa/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'iconepwa/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'iconepwa/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'iconepwa/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'iconepwa/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'iconepwa/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'iconepwa/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'iconepwa/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="192x192"  href="<%= image_path 'iconepwa/android-icon-192x192.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'iconepwa/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'iconepwa/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'iconepwa/favicon-16x16.png' %>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_path 'iconepwa/ms-icon-144x144.png' %>">
<meta name="theme-color" content="#ffffff">

app/views/shared/_modal_add_donations.html.erb
 <div class="container text-center">
  <div class="modal fade" id="donationNewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-show="<%= @donation.errors.any? %>">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= simple_form_for [:giver, @donation] do |f| %>
          <div class="modal-header">
            <h4 class="modal-title modal-titre" id="exampleModalLabel">nouveau don</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <%= f.input :deadline, label: 'Quelle est votre date limite ?', as: :string, required: false, input_html: { class: "datepicker" } %>
              <div class="col-12" id="bodycheckbox">
                <div class="" id="text-car">
                  Je me déplace ?
                </div>
                <div class="" id="btn-car">
                  <%= f.input :pick_up, input_html: { class: 'toggle1' }, label_html: { class: 'd-none'} %>
                </div>
              </div>

              <div class="modal-description">
                <%= f.input :description, placeholder: "Je donne tout, venez !", :as => :text, :input_html => {:rows => 5} %>
              </div>
              <%# <%= f.input :photo %>
              <p>Photo du don  <%= f.file_field :photo, :label => "photo" %></p>
              
              <%# au dessou c'est les deux ligne original %>
              <%# <%= f.input :photo, input_html: { hidden: true }, label: '&nbsp;'.html_safe %>
              <%# <%= f.input :photo_cache, as: :hidden %> 

              Sélectionnez une ou plusieurs catégories

              <div class="btn-group-modal pt-4" role="group" aria-label="Basic example">
                <% Donation::CATEGORIES.each do |category| %>
                  <div class="category-icon">
                    <%= f.check_box :categories,
                                    {
                                      name: 'donation[categories][]',
                                      hidden: true,
                                      id: "#{category.parameterize}-category",
                                      class: "checkbox-test"
                                    },
                                    category, nil %>
                    <%= label_tag "#{category.parameterize}-category",
                                  "",
                                  class: "checkbox-test-label",
                                  id: "#{category.parameterize}-category" %>
                  </div>
                <% end %>
              </div>
            <div class="modal-navbar-bottom">
              <div class="footer-element">
                <%= link_to donations_path do %>
                  <%= image_tag "iconefooter/home.svg" %>
                <% end %>
              </div>
              <div class="footer-element">
                <%= link_to receiver_donations_path do %>
                  <%= image_tag "iconefooter/panier.svg" %>
                <% end %>
              </div>
              <div class="footer-element" >
                <%= f.submit id: 'btn-submit-donation', value: '' %>
              </div>
              <div class="footer-element">
                <%= link_to(profile_path) do %>
                  <%= image_tag "iconefooter/user.svg" %>
                <% end %>
              </div>
              <div class="footer-element">
                <%= link_to relationships_path do %>
                  <%= image_tag "iconefooter/contact.svg" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= cl_image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_relationships_footer.html.erb
<!-- FOOTER -->
<div>
  <div class="footer">
    <div class="footer-element footer-icon <%= 'active' if current_page?('/donations') %>">
      <%= link_to donations_path do %>
        <%= cl_image_tag "iconefooter/home.svg" %>
      <% end %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/receiver/donations') %>">
      <%= link_to receiver_donations_path do %>
        <%= cl_image_tag "iconefooter/panier.svg" %>
      <% end %>
    </div>
    <div class="footer-element">
      <%= link_to new_relationship_path do %>
        <%= cl_image_tag "iconefooter/add-friends.svg" %>
      <% end %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/profile') %>">
      <%= link_to(profile_path) do %>
        <%= cl_image_tag "iconefooter/user.svg" %>
      <% end %>
    </div>
    <div class="footer-element footer-icon <%= 'active' if current_page?('/relationships') %>">
      <%= link_to relationships_path do %>
        <%= cl_image_tag "iconefooter/contact.svg" %>
      <% end %>
    </div>
  </div>
</div>