config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # devise_for :user do
  #   get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
  root to: 'pages#home'

  resources :users

  resource :profile

  resources :relationships, only: %i[index new create] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :donations, only: [:index]
  namespace :receiver do
    resources :donations, only: [:index] do
      member do
        patch :choose
      end
    end
  end

  namespace :giver do
    resources :donations, only: %i[index new create] do
      member do
        patch :confirm
      end
    end
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  CATEGORIES = ["dairy and eggs", "drinks", "fruits and vegetables", "meat and fish"]

  belongs_to :giver, class_name: "User"
  belongs_to :receiver, class_name: "User", optional: true

  validates :status, presence: true, inclusion: { in: ["pending", "chosen", "confirmed"] }
  validates :categories, presence: true

  validate :categories_in_list

  
  has_many_attached :photo

  private

  def categories_in_list
    if categories.any? { |category| !CATEGORIES.include?(category) }
      errors.add(:category, :inclusion)
    end
  end
end

app/controllers/donations_controller.rb
# frozen_string_literal: true

class DonationsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @donation = Donation.new
    @categories = params[:categories] || []
    @donations = Donation.where.not(giver: current_user)
      .where(giver: current_user.friends, status: "pending")
      .where('deadline >= ?', Date.today)
      .order("deadline")

    if @categories.present?
      @donations = @donations.where("categories && ARRAY[?]::varchar[]", @categories)
    end
  end
end

app/controllers/giver/donations_controller.rb
class Giver::DonationsController < ApplicationController
  def index
    @donations = current_user.donations.where('deadline >= ?', Date.today).order("deadline")

    @donation = Donation.new
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    @donation.giver = current_user
    if @donation.save
      redirect_to donations_path
    else
      @donations = current_user.donations.where('deadline >= ?', Date.today).order("deadline")
      render :index
    end
  end

  def confirm
    @donation = Donation.find(params[:id])
    @donation.status = 'confirmed'
    @donation.save
    redirect_to giver_donations_path
  end

  private

  def donation_params
    params.require(:donation).permit(:deadline, :pick_up, :description, categories: [])
  end
end

app/controllers/receiver/donations_controller.rb
# frozen_string_literal: true

class Receiver::DonationsController < ApplicationController
  def index
    @donation = Donation.new

    @donations = current_user.receiver_donations.where(status: ["chosen", "confirmed"]).where('deadline >= ?', Date.today).order("deadline")
  end

  def choose
    @donation = Donation.find(params[:id])
    @donation.status = 'chosen'
    @donation.receiver = current_user
    @donation.save
    redirect_to donations_path
  end
end

app/helpers/donation_helper.rb
module DonationHelper
  def donation_bg_class(deadline)
    if deadline.today?
      'bg-danger'
    elsif deadline == Date.today.tomorrow
      'bg-warning'
    else
      'bg-success'
    end
  end

  def donation_text_class(deadline)
    if deadline.today?
      'text-danger'
    elsif deadline == Date.today.tomorrow
      'text-warning'
    else
      'text-success'
    end
  end

  def donation_fill_class(deadline)
    if deadline.today?
      'fill-danger'
    elsif deadline == Date.today.tomorrow
      'fill-warning'
    else
      'fill-success'
    end
  end

  def donation_card_class(deadline)
    if deadline.today?
      'card-danger'
    elsif deadline == Date.today.tomorrow
      'card-warning'
    else
      'card-success'
    end
  end
end

app/views/giver/donations/index.html.erb
<div class="top-bar">
  <ul class="list-inline tabs-underlined">
    <li>
      <h3><%= link_to "Fil de dons", '/donations', class: "tab-underlined", id: "list-don" %></h3>
    </li>
    <li class="tabs-pipe"> | </li>
    <li>
      <h3><a href="#" class="tab-underlined active right">Je donne</a></h3>
    </li>
  </ul>
</div>

<div class="container container-list" id="userlist-don">
  <div class= "row justify-content-center">
    <% if @donations.empty? %>
      <div class="text-center">
        <h3>N'hésite pas à donner ! Clique sur l'icône "+" pour créer un don</h3>
        <%= image_tag "iconefooter/signeplus.svg", data: { toggle: "modal", target: "#donationNewModal" } %>
      </div>
    <% else %>
    <% @donations.each do |donation| %>
      <div class="panel panel-default mb-2">
        <div class="panel-heading">
          <div class="col-12 card spoiler-trigger" data-toggle="collapse">
            <div class="card-avatar <%= donation_bg_class(donation.deadline) %>">
              <div class="avatar" style="background-color: #FAFAFA">
                <% if donation.status == "chosen" %>
                  <%= image_tag(donation.receiver.avatar, height: 64, width: 64, crop: :fill, gravity: :face) %>
                <% elsif donation.status == "confirmed" %>
                  <%= image_tag(donation.receiver.avatar, height: 64, width: 64, crop: :fill, gravity: :face) %>
                <% else donation.status == "pending" %>
                  <%= image_tag("iconecard/panier-sad.svg", height: 64, width: 64, crop: :fill, gravity: :face) %>
                <% end %>
              </div>
            </div>

            <div class="card-content">
              <div class="row-card-content" id="first-row">
                <div class="card-content-deadline">
                  <p class="<%= donation_text_class(donation.deadline) %>">
                    <%= render 'icons/horloge', svg_class: donation_fill_class(donation.deadline) %>&thinsp;
                    <%= donation.deadline.strftime("%d.%m.%Y") %>
                  </p>
                </div>
                  <% if donation.pick_up %>
                    <div class="card-content-voiture">
                      <%= image_tag "iconecard/car.svg" %>
                    </div>
                  <% end %>
              </div>

              <div class="row-card-content" id="second-row">
                <div class="card-content-username">
                  <% if donation.status == "chosen" && donation.pick_up == true %>
                    <p>Je dois me déplacer.</p>
                  <% elsif donation.status == "chosen" && donation.pick_up == false %>
                    <p><%= donation.receiver.first_name %> va passer.</p>
                  <% elsif donation.status == "confirmed" %>
                    <p> Zéro gaspi !</p>
                  <% else donation.status == "pending" %>
                    <p> Disponible !</p>
                  <% end %>
                </div>
                <div class="card-content-categories">
                  <div class="card-content-categories-status">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="panel-collapse collapse out">
          <div class="panel-body">
            <div class= "accordeon" >
              <div class="d-flex justify-content-between">
                <div class="accordeon-content">
                  <%= simple_format donation.description %>
                </div>
                <% if donation.photo.present? %>
                  <div class ="accordeon-image p-2">
                    <%# <%= image_tag(donation.photo, height: 107, width: 114, crop: :fill) %>
                    <%# au dessus la ligne original en dessou la variant pour active storage %>
                    <%= cl_image_tag donation.photo.variant(resize: "107x114!").processed %>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- <div class= "row accordeon" >
                <div class="accordeon-content col-7">
                  <%= simple_format donation.description %>
                </div>
                <%#if donation.photo.present? %>
                  <div class ="accordeon-image col-5">
                    <%#= cl_image_tag(donation.photo, height: 107, width: 114, crop: :fill) %>
                  </div>
                <#% end %>
              </div> -->
              <% if donation.status == "chosen" %>
                <%= link_to("Don récupéré", confirm_giver_donation_path(donation), method: :patch, class: "btn btn-primary btn-block btn-accordeon") %>
              <% end %>
          </div>
        </div>
      </div>
    <% end%>
    <% end%>
  </div>
</div>

<!-- MODAL DONATION NEW -->
<%= render 'shared/modal_add_donations' %>

<%= render 'shared/donations_footer' %>

app/views/giver/donations/new.html.erb
 <div class="container text-center">
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-show="<%= @donation.errors.any? %>">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= simple_form_for [:giver, @donation] do |f| %>
          <div class="modal-header">
            <h4 class="modal-title modal-titre" id="exampleModalLabel">nouveau don</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <%= f.input :deadline, label: 'Quelle est votre date limite ?', as: :string, required: false, input_html: { class: "datepicker" } %>
              <div class="col-12" id="bodycheckbox">

                  <div class="" id="text-car">
                    Je me déplace ?
                  </div>
                  <div class="" id="btn-car">
                    <%= f.input :pick_up, input_html: { class: 'toggle1' }, label_html: { class: 'd-none'} %>
                  </div>

              </div>

              <div class="modal-description">
              <%= f.input :description, placeholder: "Je donne tout, venez !", :as => :text, :input_html => {:rows => 5} %>
              </div>

                <%# <%= f.input :photo, input_html: { hidden: true }, label: '&nbsp;'.html_safe %>
                <%# <%= f.input :photo %>
                <%# <%= f.input :photo_cache, as: :hidden %>
                <%# <%= f.input :photo, as: :hidden %>
                <!-- ligne du dessus 2019 en dessous test 2020 -->
                <p>Photo du don  <%= f.file_field :photo, :label => "photo" %></p>


              Sélectionnez une ou plusieurs catégories

              <div class="btn-group-modal pt-4" role="group" aria-label="Basic example">
                <% Donation::CATEGORIES.each do |category| %>
                  <div class="category-icon">
                    <%= f.check_box :categories,
                                    {
                                      name: 'donation[categories][]',
                                      hidden: true,
                                      id: "#{category.parameterize}-category",
                                      class: "checkbox-test"
                                    },
                                    category, nil %>
                    <%= label_tag "#{category.parameterize}-category",
                                  "",
                                  class: "checkbox-test-label",
                                  id: "#{category.parameterize}-category" %>
                  </div>
                <% end %>
              </div>
            <div class="modal-navbar-bottom">
              <div class="footer-element">
                <%= link_to donations_path do %>
                  <%= image_tag "iconefooter/home.svg" %>
                <% end %>
              </div>
              <div class="footer-element">
                <%= link_to receiver_donations_path do %>
                  <%= image_tag "iconefooter/panier.svg" %>
                <% end %>
              </div>
              <div class="footer-element" >
                <%= f.submit id: 'btn-submit-donation', value: '' %>
              </div>
              <div class="footer-element">
                <%= link_to(profile_path) do %>
                  <%= image_tag "iconefooter/user.svg" %>
                <% end %>
              </div>
              <div class="footer-element">
                <%= link_to relationships_path do %>
                  <%= image_tag "iconefooter/contact.svg" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>